services:
  - type: web
    name: repo-viz-server
    env: node
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
